swagger: '2.0'
info:
  version: 1.0.0
  title: JLPT Feedback API
  description: A RESTful API to store feedback from JLPT exam app
schemes:
  - https
host: jlpt-app-backend.vercel.app
consumes:
  - application/json
produces:
  - application/json
paths:
  /feedback:
    post:
      summary: Create a new feedback
      parameters:
        - in: body
          name: feedback
          description: The feedback object to be created
          schema:
            type: object
            required:
              - uid
              - questionJSON
              - feedback
              - explain
            properties:
              uid:
                type: string
              questionJSON:
                type: string
              feedback:
                type: string
                enum: [good, bad]
              comment:
                type: string
              explain:
                type: string
      responses:
        201:
          description: Created
          schema:
            type: object
            properties:
              _id:
                type: string
              uid:
                type: string
              questionJSON:
                type: string
              feedback:
                type: string
                enum: [good, bad]
              comment:
                type: string
              explain:
                type: string
        400:
          description: Bad Request
  /feedback/good-uids:
    get:
      summary: Get a list of uids with good feedback
      responses:
        200:
          description: A list of uids with good feedback
          schema:
            type: array
            items:
              type: string
  /feedback/question/{uid}:
    get:
      summary: Get question JSON by uid
      parameters:
        - in: path
          name: uid
          type: string
          required: true
          description: The uid of the feedback
      responses:
        200:
          description: The question JSON related to the uid
          schema:
            type: object
            properties:
              questionJSON:
                type: string
        404:
          description: Feedback not found for the provided uid
