# swagger.yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: Questions API
  description: A RESTful API to perform CRUD operations on questions
schemes:
  - https
# host: jlpt-app-backend.vercel.app
host: jlpt-app-backend-jojojen.vercel.app
definitions:
  Question:
    type: object
    properties:
      _id:
        type: string
      questionJSON:
        type: string
      explain:
        type: string
      feedbacks:
        type: array
        items:
          type: object
          properties:
            rating:
              type: integer
              minimum: 0
              maximum: 1
            comment:
              type: string
  User:
    type: object
    properties:
      _id:
        type: string
      lastLoginDate:
        type: string
      serviceUsage:
        type: object
        properties:
          createQuestionByGPT:
            type: integer
      album:
        type: array
        items:
          type: string

consumes:
  - application/json
produces:
  - application/json
paths:
  /question:
    post:
      summary: Create a new question
      parameters:
        - in: body
          name: question
          description: The question object to be created
          schema:
            type: object
            required:
              - _id
              - questionJSON
              - explain
            properties:
              _id:
                type: string
              questionJSON:
                type: string
              explain:
                type: string
              feedbacks:
                type: array
                items:
                  type: object
                  properties:
                    rating:
                      type: integer
                      minimum: 0
                      maximum: 1
                    comment:
                      type: string
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Question'
        400:
          description: Bad Request

  /question/{id}:
    get:
      summary: Get question by ID
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: The ID of the question
      responses:
        200:
          description: The question object
          schema:
            $ref: '#/definitions/Question'
        404:
          description: Question not found

    put:
      summary: Update question by ID
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: The ID of the question
        - in: body
          name: question
          description: The question object with updated fields
          schema:
            $ref: '#/definitions/Question'
      responses:
        200:
          description: The updated question object
          schema:
            $ref: '#/definitions/Question'
        400:
          description: Bad Request
        404:
          description: Question not found

    delete:
      summary: Delete question by ID
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: The ID of the question
      responses:
        200:
          description: Question deleted successfully
          schema:
            type: object
            properties:
              message:
                type: string
        404:
          description: Question not found

  /question/{id}/comment:
    post:
      summary: Add a new comment to a specific question
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: The ID of the question
        - in: body
          name: comment
          description: The comment object to be added
          schema:
            type: object
            required:
              - rating
              - comment
            properties:
              rating:
                type: integer
                minimum: 0
                maximum: 1
              comment:
                type: string
      responses:
        200:
          description: The updated question object with the new comment
          schema:
            $ref: '#/definitions/Question'
        400:
          description: Bad Request
        404:
          description: Question not found
  /questions/top:
    get:
      summary: Get N questions with at least one rating of 1
      parameters:
        - in: query
          name: n
          type: integer
          required: true
          description: The number of questions to retrieve
      responses:
        200:
          description: A list of N questions with at least one rating of 1
          schema:
            type: array
            items:
              $ref: '#/definitions/Question'
        400:
          description: Bad Request

  /user/login:
    post:
      summary: Login or create a new user
      parameters:
        - in: body
          name: user
          description: The user object to be logged in or created
          schema:
            type: object
            required:
              - _id
            properties:
              _id:
                type: string
      responses:
        200:
          description: Logged in or created a new user
          schema:
            type: object
            properties:
              _id:
                type: string
              lastLoginDate:
                type: string
              serviceUsage:
                type: object
                properties:
                  createQuestionByGPT:
                    type: integer
              album:
                type: array
        400:
          description: Bad Request
        500:
          description: Internal Server Error